# More details on how to configure the Travis build
# https://docs.travis-ci.com/user/customizing-the-build/

language: scala

jdk: openjdk11
env: JDK='Oracle JDK 11'

#Skipping install step to avoid having Travis run arbitrary './gradlew assemble' task
# https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install:
  - true

#Don't build tags
branches:
  except:
  - /^v\d/


script:
  # To validate changes, we run building and bintray upload in dry run. This happens on every build, even PRs.
  # To publish, we perform github release and perform bintray upload (no dry run). This only for main branch builds.
  - >
    ./gradlew build bintrayUpload -PbintrayDryRun
    && if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "release/1.x" ];
      then ./gradlew bintrayUpload githubRelease; fi
